# Generated by Django 3.1.7 on 2021-03-20 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixnip', models.CharField(default='PL', max_length=2)),
                ('nip', models.IntegerField()),
                ('nazwa', models.CharField(max_length=100)),
                ('pelna_nazwa', models.CharField(max_length=255)),
                ('ulica', models.CharField(max_length=100)),
                ('miejscowosc', models.CharField(max_length=100)),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('telfon', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Lokalizacja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza.klient')),
            ],
        ),
    ]
