# Generated by Django 3.1.7 on 2021-03-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='nip',
            field=models.CharField(max_length=10),
        ),
    ]
