# Generated by Django 3.1.7 on 2021-03-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0002_auto_20210320_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='lokalizacja',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='lokalizacja',
            name='extra_info',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='lokalizacja',
            name='kod_pocztowy',
            field=models.CharField(default=-100, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lokalizacja',
            name='miejscowosc',
            field=models.CharField(default='xyz', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lokalizacja',
            name='telfon',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='lokalizacja',
            name='ulica',
            field=models.CharField(default='xyz', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='klient',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='klient',
            name='telfon',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
