# Generated by Django 3.1.7 on 2021-03-30 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0003_auto_20210322_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licencja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza.klient')),
                ('lokazliacja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='baza.lokalizacja')),
            ],
        ),
    ]
