# Generated by Django 3.1.7 on 2021-03-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0004_licencja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licencja',
            name='klient',
        ),
        migrations.AddField(
            model_name='licencja',
            name='wersja_programu',
            field=models.IntegerField(choices=[(1, 'XL-1'), (3, 'XL-3'), (5, 'XL-5')], default=1),
            preserve_default=False,
        ),
    ]
