# Generated by Django 3.1.7 on 2021-03-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0005_auto_20210330_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licencja',
            old_name='lokazliacja',
            new_name='lokalizacja',
        ),
    ]
