# Generated by Django 3.1.7 on 2021-03-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0006_auto_20210330_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moduly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='licencja',
            name='modul',
            field=models.ManyToManyField(to='baza.Moduly'),
        ),
    ]
