# Generated by Django 3.1.7 on 2021-04-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0007_auto_20210331_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencja',
            name='moduly',
            field=models.CharField(choices=[('XXX', 'xxx'), ('YYY', 'yyy')], default='xxx', max_length=100),
            preserve_default=False,
        ),
    ]
