# Generated by Django 3.1.7 on 2021-04-08 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0008_licencja_moduly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licencja',
            name='moduly',
        ),
    ]
